import {
  datasourceApp,
  datasourceCLI,
  environment,
  logger,
  routes,
  v1Routes,
  swaggerConfig,
  app,
  server,
  baseException,
  validationException,
  _exception,
  errorHandlerMiddleware,
  validationMiddleware,
  _middlewares,
  unauthorizedException,
  forbiddenException,
  notfoundException,
  conflicException,
  badRequestException,
  seed,
} from './templates.js';

export const structure = {
  src: {
    config: [
      { file: 'database.ts', template: datasourceApp },
      { file: 'environment.ts', template: environment },
      { file: 'logger.ts', template: logger },
    ],
    database: {
      migrations: [{ file: 'index.ts', template: '' }],
      seeds: [{ file: 'index.ts', template: '' }],
      _files: [{ file: 'database.ts', template: datasourceCLI }],
    },
    entities: [{ file: 'index.ts', template: '' }],
    repositories: [{ file: 'index.ts', template: '' }],
    services: [{ file: 'index.ts', template: '' }],
    controllers: [{ file: 'index.ts', template: '' }],
    middlewares: {
      _files: [
        { file: 'index.ts', template: _middlewares },
        { file: 'error-handler.ts', template: errorHandlerMiddleware },
        { file: 'dto-validation.ts', template: validationMiddleware },
      ],
    },
    validators: [{ file: 'index.ts', template: '' }],
    routes: {
      v1: [{ file: 'index.ts', template: v1Routes }],
      _files: [{ file: 'index.ts', template: routes }],
    },
    types: [{ file: 'index.ts', template: '' }],
    utils: [{ file: 'index.ts', template: '' }],
    constants: [{ file: 'index.ts', template: '' }],
    jobs: [{ file: 'index.ts', template: '' }],
    queues: [{ file: 'index.ts', template: '' }],
    exceptions: {
      _files: [
        { file: 'index.ts', template: _exception },
        { file: 'base-exception.ts', template: baseException },
        { file: 'validation-exception.ts', template: validationException },
        { file: 'unauthorized-exception.ts', template: unauthorizedException },
        { file: 'forbidden-exception.ts', template: forbiddenException },
        { file: 'notfound-exception.ts', template: notfoundException },
        { file: 'conflic-exception.ts', template: conflicException },
        { file: 'bad-request-exception.ts', template: badRequestException },
      ],
    },
    decorators: [{ file: 'index.ts', template: '' }],
    docs: {
      _files: [{ file: 'swagger.config.ts', template: swaggerConfig }],
    },
    _files: [
      { file: 'app.ts', template: app },
      { file: 'server.ts', template: server },
    ],
  },
  tests: {
    unit: [{ file: 'index.ts', template: '' }],
    integration: [{ file: 'index.ts', template: '' }],
    e2e: [{ file: 'index.ts', template: '' }],
    fixtures: [{ file: 'index.ts', template: '' }],
    helpers: [{ file: 'index.ts', template: '' }],
    _files: [{ file: 'setup.ts', template: '' }],
  },
  scripts: {
    _files: [{ file: 'seed.ts', template: seed }],
  },
};
