export const structure = {
  src: {
    config: ['database.ts', 'environment.ts', 'logger.ts'],
    database: {
      migrations: ['index.ts'],
      seeds: ['index.ts'],
      _files: ['datasource.ts'],
    },
    entities: ['index.ts'],
    repositories: ['index.ts'],
    services: ['index.ts'],
    controllers: ['index.ts'],
    middlewares: ['index.ts'],
    validators: ['index.ts'],
    routes: {
      v1: ['index.ts'],
    },
    types: ['index.ts'],
    utils: ['index.ts'],
    constants: ['index.ts'],
    jobs: ['index.ts'],
    queues: ['index.ts'],
    exceptions: ['index.ts'],
    decorators: ['index.ts'],
    docs: {
      _files: ['swagger.config.ts'],
    },
    _files: ['app.ts', 'server.ts'],
  },
  tests: {
    unit: ['index.ts'],
    integration: ['index.ts'],
    e2e: ['index.ts'],
    fixtures: ['index.ts'],
    helpers: ['index.ts'],
    _files: ['setup.ts'],
  },
  scripts: ['index.ts'],
  logs: ['.gitkeep'],
};
